feat: whitebox scheme adjustment
deepin-community/lightdm pull request #1
Opened 2023-08-07 13:32 UTC by chenchongbiao

* 新白盒方案，简化lightdm pam流程
* 修复错误的在auth阶段使用autostart用法

Log: whitebox scheme adjustment

2023-08-08 09:50 UTC, UTsweetyfish requested changes
如下，以及没更新 changelog

2023-08-08 09:50 UTC, UTsweetyfish commented on debian/patches/0002-feat-whitebox-scheme-adjustment.patch
> ++-session    optional    pam_deepin_keyring.so
这个 pam_deepin_keyring.so 是哪里来的？我没找到

2023-08-08 09:50 UTC, UTsweetyfish commented on debian/patches/0002-feat-whitebox-scheme-adjustment.patch
> ++-auth        optional   pam_deepin_keyring.so
这个 pam_deepin_keyring.so 是哪里来的？我没找到

2023-08-09 02:06 UTC, chenchongbiao commented on debian/patches/0002-feat-whitebox-scheme-adjustment.patch
> ++-auth        optional   pam_deepin_keyring.so
安装了deepin-keyring-white项目才有有，闭源，用来解决自动弹密钥问题的。

2023-08-09 02:07 UTC, chenchongbiao commented on debian/patches/0002-feat-whitebox-scheme-adjustment.patch
> ++-session    optional    pam_deepin_keyring.so
同下

2023-08-09 12:09 UTC, wineee commented on debian/patches/0002-feat-whitebox-scheme-adjustment.patch
> ++-auth        optional   pam_deepin_keyring.so
那应该 debian/control 加一下推荐依赖

2023-08-09 12:34 UTC, Rabenda commented on debian/patches/0002-feat-whitebox-scheme-adjustment.patch
> ++-auth        optional   pam_deepin_keyring.so
> 安装了deepin-keyring-white项目才有有，闭源，用来解决自动弹密钥问题的。

那应该做可选的 强硬依赖会有问题的

2023-08-09 12:59 UTC, chenchongbiao commented on debian/patches/0002-feat-whitebox-scheme-adjustment.patch
> ++-auth        optional   pam_deepin_keyring.so
> > 安装了deepin-keyring-white项目才有有，闭源，用来解决自动弹密钥问题的。
> 
> 那应该做可选的 强硬依赖会有问题的

确实 我先整理一下相关项目

2023-08-10 01:28 UTC, chenchongbiao commented
linuxdeepin/developer-center/issues/3572

2023-08-10 03:38 UTC, chenchongbiao commented
/integrate

2023-08-10 03:40 UTC, UTsweetyfish commented
> /integrate

...?

2023-08-10 06:52 UTC, chenchongbiao commented
/integrate

2023-08-14 05:31 UTC, Zeno-sole commented
@Rabenda  add review

2023-08-16 03:04 UTC, Zeno-sole commented
/approve

2023-08-29 02:16 UTC, chenchongbiao commented
/check obs

2023-08-29 02:21 UTC, merged